name: Compiler Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-13]

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Compiler avec PyInstaller (Windows)
      if: runner.os == 'Windows'
      run: |
        pyinstaller --noconsole --onefile --name="BM_PROD" app.py

    - name: Compiler avec PyInstaller (macOS Catalina)
      if: runner.os == 'macOS'
      run: |
        pyinstaller --noconsole --onefile --name="BM_PROD_MAC" app.py

    - name: Sauvegarder l'exécutable Windows
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: application-windows
        path: dist/BM_PROD.exe

    - name: Sauvegarder l'application macOS Catalina
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v4
      with:
        name: application-macos-catalina
        path: dist/BM_PROD_MAC.app
